[features]
seeds = false
[programs.devnet]
whitelist = "GAChMFE4jNfB7XXfx6dEoPGWV7UxNRRdxois4FcmBVxe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/julian/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
